version: '3'
services:
  prisma-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "3000:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile     
    depends_on:
      - prisma-postgres
    env_file:
      - .env  # Load environment variables from .env file
    command: ["/app/start.sh"]
    

volumes:
  postgres-data:

